# docker-compose up -d
version: '3.5'

services:
  bind9:
    restart: always
    image: rnemeth90/docker-bind
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    volumes:
    - ./bind9:/data # Change volume path